resources/assets/js/components/knocksuserabout.vue

22 feb 18 (22)

---

resources/views/user/home.blade.php

creation editsss

---

resources/views/user/profile.blade.php

24 feb 18 (3) -profile

---

resources/views/user/profile.blade.php

24 feb 18 (4) -profile

---

resources/assets/js/components/knocksrecorder.vue

knocks recorder -- fixed resetting the record stream and stop using the client microphone when not needed.

2 mar 18 (3) --knocksrecorder

---

app/Http/Controllers/EducationController.php
resources/assets/js/components/knocksusereducation.vue
resources/assets/js/components/knocksusereducationedit.vue
resources/assets/js/components/knocksuserhigheducation.vue
resources/assets/js/components/knocksuserhobby.vue
resources/assets/js/components/knocksusersport.vue

02 mar 18 (4)

---

app/Http/Controllers/UserController.php
resources/assets/js/components/knockselinput.vue

userController search fixed. 
knockselinput added autocomplete feature.

2 mar 18 (5)

---

app/Http/Controllers/BlobController.php
app/Http/Controllers/GroupMemberController.php
resources/assets/js/app.js
resources/assets/js/components/knockscroppie.vue
resources/assets/js/components/knocksgroupmembers.vue
resources/assets/sass/app.scss
resources/views/groups/group.blade.php
routes/web.php

Groups static pages
App.JS
App.Scss
new Component Knocksgroupmembers
Updates in Blob Stack

2 mar 18(6)

---

resources/assets/js/components/knockspagesearch.vue

11 mar 18 (1)

---

resources/assets/js/components/knockspagesearch.vue

11 mar 18 (3)

---

app/Group.php
app/Http/Controllers/GroupController.php
app/Http/Controllers/UserRequestController.php
resources/assets/js/components/knocksgroupjoining.vue
resources/assets/js/components/knocksgroupmembers.vue
resources/assets/js/components/knocksgrouppictures.vue
resources/assets/js/components/knocksgroupsettings.vue
resources/assets/js/components/knocksgroupvoices.vue
resources/assets/js/components/knocksusershortcut.vue
resources/views/groups/group.blade.php
routes/web.php

23 mar 18(1)

---

resources/assets/js/components/knocksprivacyadjustments.vue

23 mar 18 (3)

---

resources/assets/js/components/knocksreply.vue

23 mar 18 (6)

---

resources/assets/js/components/knockstaps.vue

23 mar 18 (8)

---

resources/assets/js/components/knockselbutton.vue

knockselbutton -- preconditions added

23 mar 18 (9)

---

resources/assets/js/components/knocksfileviewer.vue

23 mar 18 (10)

---

resources/assets/js/components/knock.vue

knocks reacrtor , knock , knocker

23 mar 18 (13)

---

app/Reply.php

23 mar 18 (19)

---

app/Comment.php

23 mar 18 (20)

---

app/User.php

23 mar 18 (21)

---

app/Http/Controllers/UserController.php

23 mar 18 (22)

---

app/Http/Controllers/SavedPresetsController.php

23 mar 18 (23)

---

routes/web.php

23 mar 18(26)

---

resources/assets/js/components/knock.vue

24 mar 18 (6)

---

resources/assets/js/components/knocksbutton.vue

24 mar 18 (7)

---

resources/assets/js/components/knocksknock.vue

24 mar 18 (8)

---

resources/assets/js/components/knocksknockinjector.vue

24 mar 18 (9)

---

public/css/app.css
resources/assets/js/components/knockshashtag.vue
resources/assets/js/components/knocksusercircles.vue
resources/assets/sass/app.scss
resources/views/layouts/sidebar.blade.php
routes/web.php

Knockshashtags
